[build]
  base = "ai-studio-zip-project"
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/photo"
  to = "/photo.html"
  status = 200

[[redirects]]
  from = "/photo-portfolio"
  to = "/photo.html"
  status = 200

[[redirects]]
  from = "/project"
  to = "/project.html"
  status = 200
